# Multivariable Linear Regression

- hypothesis  
H(x1, x2, x3) = x1w1 + x2w2 + x3w3  
X * W = Y  
[5, 3] X [3, 1] = [5, 1]  
  
아래 코드는 without matrix

In [11]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196, 142]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1*w1 + x2*w2 + x3*w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
# Initialize global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n ", hy_val)

0 Cost:  53779.7 
Prediction:
  [-55.121677 -61.94749  -63.156353 -70.65777  -44.506466]
100 Cost:  1.633775 
Prediction:
  [150.68306 185.34079 180.53908 194.7194  144.09473]
200 Cost:  1.5766627 
Prediction:
  [150.72086 185.31459 180.55026 194.73065 144.0577 ]
300 Cost:  1.5224245 
Prediction:
  [150.7576  185.28908 180.5611  194.74167 144.02158]
400 Cost:  1.4709707 
Prediction:
  [150.7933  185.26428 180.57164 194.75243 143.98637]
500 Cost:  1.4221108 
Prediction:
  [150.82803 185.24016 180.58186 194.76295 143.95206]
600 Cost:  1.3757327 
Prediction:
  [150.8618  185.21669 180.5918  194.77327 143.91862]
700 Cost:  1.3317236 
Prediction:
  [150.8946  185.19385 180.60144 194.78337 143.88606]
800 Cost:  1.2899252 
Prediction:
  [150.92653 185.17168 180.61082 194.79327 143.85432]
900 Cost:  1.2502286 
Prediction:
  [150.95757 185.15009 180.61993 194.80298 143.8234 ]
1000 Cost:  1.2125227 
Prediction:
  [150.98772 185.1291  180.62877 194.81245 143.79321]
1100 Cost:  1.1767062 
Predicti

In [9]:
import tensorflow as tf

x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.],
         [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
# Initialize global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n ", hy_val)

0 Cost:  90610.3 
Prediction:
  [[-119.59638]
 [-133.61946]
 [-137.06554]
 [-149.06975]
 [ -99.17397]]
100 Cost:  7.7013373 
Prediction:
  [[147.59175]
 [187.31554]
 [179.26399]
 [195.3926 ]
 [145.57794]]
200 Cost:  7.302008 
Prediction:
  [[147.69759]
 [187.24301]
 [179.29646]
 [195.41573]
 [145.48308]]
300 Cost:  6.923726 
Prediction:
  [[147.8006 ]
 [187.17242]
 [179.32806]
 [195.43825]
 [145.39075]]
400 Cost:  6.565451 
Prediction:
  [[147.90086]
 [187.10374]
 [179.35884]
 [195.46014]
 [145.30092]]
500 Cost:  6.226003 
Prediction:
  [[147.99846]
 [187.03687]
 [179.3888 ]
 [195.48145]
 [145.21347]]
600 Cost:  5.9045134 
Prediction:
  [[148.09343]
 [186.97179]
 [179.41792]
 [195.5022 ]
 [145.12837]]
700 Cost:  5.5999455 
Prediction:
  [[148.18587]
 [186.90843]
 [179.44629]
 [195.52235]
 [145.04553]]
800 Cost:  5.31145 
Prediction:
  [[148.27586]
 [186.8468 ]
 [179.4739 ]
 [195.54199]
 [144.96494]]
900 Cost:  5.038213 
Prediction:
  [[148.36343]
 [186.7868 ]
 [179.5008 ]
 [195.56107]
